name: ci

on: [ push, pull_request ]

jobs:
  tests:
    strategy:
      matrix:
        python-version: [
          '3.10',
          '3.11',
          '3.12',
          '3.13',
          'pypy-3.10',
          'pypy-3.11',
        ]
        os: [ubuntu]
      fail-fast: true
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    - uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
        path: |
          ~/.cache/uv
          ~/.cargo
        restore-keys: |
          ${{ runner.os }}-uv-
    - name: Install dependencies
      run: |
        uv sync --group dev
    - name: Run lint & tests
      run: |
        sudo apt-get install -y tesseract-ocr tesseract-ocr-por
        make ci SKIP_STYLE=true
    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v3
    #   with:
    #     file: ./coverage.xml
    #     fail_ci_if_error: true
